spring:
  application:
    name: app

  config:
    import:
      - aws-secretsmanager:/app/db/url?prefix=db.
      - aws-secretsmanager:/app/db/username?prefix=db.
      - aws-secretsmanager:/app/db/password?prefix=db.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  cloud:
    aws:
      region:
        static: ap-northeast-1
